# Generated by Django 6.0.3 on 2026-03-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_comment_id_alter_like_id_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
